### ISSUE TITLE
Bug & Feature on beta 2

### ISSUE THREAD

**Issue by RudiZhang** [vatis-project/vatis#38] opened 2022-05-17 23:38 UTC
BUGs:
![image](https://user-images.githubusercontent.com/40914896/168929149-01ec502b-b7bf-46bc-9416-e4296f186338.png)
for TL, i don't know why but it shows together

![image](https://user-images.githubusercontent.com/40914896/169159342-38c92b67-c462-4009-bfdc-ba740d95bc5d.png)
I don't have any option for arrival

![image](https://user-images.githubusercontent.com/40914896/169159426-2393ceb8-9e28-4288-8af2-3fecbad71732.png)
It read as "runway one", but for non-FAA it should be runway zero one

![image](https://user-images.githubusercontent.com/40914896/169159548-15fc5f78-168e-4710-9083-8e06505d6746.png)
![image](https://user-images.githubusercontent.com/40914896/169159573-58e132c9-d0df-4a51-9f38-ce6d1d1397b8.png)
no [WIND] and CAVOK text display for non-FAA format, but read correctly

no text ATIS showing when using external ATIS

for external ATIS, ATIS letter read as "a b c", i don't know why

Feature:
Add Transition Altitude maybe?

make [TL] logic like if no value on [TL] then don't show [TL]? so people can make a commen temple

set ATIS code before connect?

cloud shows in metric on text?

airport condition/NOTAM fetch from main pannel?

**Comment by mythicfci** [comment] 2022-05-22 04:50
I can confirm I'm having the same issue with vATIS not adding a space between "Transition level" and the number.

![image](https://user-images.githubusercontent.com/49729038/169679238-d6a87f3f-b2d4-4989-8993-b69e5980fc99.png)

**Comment by justinshannon** [comment] 2023-03-17 20:38
The next version should fix the following issues (not yet released):

- Add space after "transition level"
- Read leading zero on numbers (non-FAA format)
- Fix missing WIND and CAVOK
- Cloud height converted to metric (if enabled)

The ATIS code cannot be set before connecting. This would require lots of changes to the current codebase.

The issue with vATIS not reading the ATIS code correctly from an external ATIS generator is not an easy fix. vATIS just reads what the external ATIS generator (e.g. UniATIS) produces. vATIS doesn't know the ATIS template format, so it's difficult to parse and replace the ATIS code with the correct phonetic.

I am going to close this issue, since it is so old. Once the new vATIS version is released, feel free to open a new Github issue if you are still experiencing any formatting or functionality issues.

**Closed by justinshannon** 2023-03-17 20:38 UTC
