### ISSUE TITLE
Error when Collapsing to MiniDisplay (beta 10)

### ISSUE THREAD

**Issue by dbsirota** [vatis-project/vatis#129] opened 2023-04-30 00:11 UTC
When attempting to collapse vATIS to the MiniDisplay, the following error appears: https://prnt.sc/3ozO26oungSY

The window then only partially functions as a result, with the airports list cut off.

**Comment by justinshannon** [comment] 2023-04-30 02:21
Click the “Details” button and copy and paste the error text here.

**Comment by dbsirota** [comment] 2023-04-30 19:04
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vatsim.Vatis.UI.MiniDisplayForm.<>c__DisplayClass15_1.<RefreshDisplay>b__4(Object sender, EventArgs args) in Vatsim.Vatis\UI\MiniDisplayForm.cs:line 155
   at Vatsim.Vatis.UI.MainForm.<>c__DisplayClass25_0.<<RefreshAtisComposites>b__6>d.MoveNext() in Vatsim.Vatis\UI\MainForm.cs:line 414
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Private.CoreLib.dll
----------------------------------------
vATIS
    Assembly Version: 4.0.0.11
    Win32 Version: 4.0.0.11
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/vATIS.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.dll
----------------------------------------
Ninject
    Assembly Version: 3.3.6.0
    Win32 Version: 3.3.6.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Ninject.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/netstandard.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1623.17402
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.ComponentModel.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Newtonsoft.Json.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1623.17402
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Threading.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Threading.Thread.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Collections.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Collections.Concurrent.dll
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 5.0.1.0
    Win32 Version: 5.0.1.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Serilog.Sinks.File.dll
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Serilog.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Linq.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Text.Encoding.Extensions.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.IO.FileSystem.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Private.Uri.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Linq.Expressions.dll
----------------------------------------
Ninject.Extensions.Factory
    Assembly Version: 3.3.3.0
    Win32 Version: 3.3.3.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Ninject.Extensions.Factory.dll
----------------------------------------
Castle.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Castle.Core.dll
----------------------------------------
Vatsim.Network
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Vatsim.Network.dll
----------------------------------------
System.Reflection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Reflection.dll
----------------------------------------
System.Reflection.TypeExtensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Reflection.TypeExtensions.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Reflection.Primitives.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.Extensions.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Collections.Specialized.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Reflection.Emit.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Castle.Core.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Castle.Core.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Memory.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.ObjectModel.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1623.17402
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Accessibility.dll
----------------------------------------
CredentialManagement
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/CredentialManagement.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.Numerics.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Private.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Private.CoreLib.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1623.17402
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Drawing.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Security.Permissions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Security.Permissions.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Resources.Extensions.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Net.Http.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Net.Http.Json.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Text.Json.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.Intrinsics.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
GeoVR.Connection
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/GeoVR.Connection.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Net.ServicePoint.dll
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.11.13229
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/NLog.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Management
    Assembly Version: 7.0.0.1
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Management.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Microsoft.Win32.Registry.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Text.RegularExpressions.dll
----------------------------------------
RestSharp
    Assembly Version: 106.12.0.0
    Win32 Version: 106.12.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/RestSharp.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Windows.Extensions.dll
----------------------------------------
System.Security.Cryptography.Csp
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Security.Cryptography.Csp.dll
----------------------------------------
System.IdentityModel.Tokens.Jwt
    Assembly Version: 6.12.2.0
    Win32 Version: 6.12.2.20820
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.IdentityModel.Tokens.Jwt.dll
----------------------------------------
Microsoft.IdentityModel.Tokens
    Assembly Version: 6.12.2.0
    Win32 Version: 6.12.2.20820
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Microsoft.IdentityModel.Tokens.dll
----------------------------------------
Microsoft.IdentityModel.Logging
    Assembly Version: 6.12.2.0
    Win32 Version: 6.12.2.20820
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Microsoft.IdentityModel.Logging.dll
----------------------------------------
Microsoft.IdentityModel.JsonWebTokens
    Assembly Version: 6.12.2.0
    Win32 Version: 6.12.2.20820
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Microsoft.IdentityModel.JsonWebTokens.dll
----------------------------------------
GeoVR.Shared
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/GeoVR.Shared.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Net.Requests.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Net.WebHeaderCollection.dll
----------------------------------------
Concentus
    Assembly Version: 1.1.6.0
    Win32 Version: 1.1.6.0
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/Concentus.dll
----------------------------------------
MessagePack.Annotations
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.75.31876
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/MessagePack.Annotations.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Diagnostics.Process.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Runtime.Loader.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1623.17311
    CodeBase: file:///C:/Users/bowli/AppData/Local/vATIS-4.0/Application/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************

**Comment by justinshannon** [comment] 2023-04-30 21:47
What airport(s) do you have configured? Give me the ICAO identifiers.

**Comment by dbsirota** [comment] 2023-04-30 21:48
This file is for KEWR, KCDW, KMMU, and KTEB. This has also occurred on a separate file for KJFK and KFRG.

**Comment by justinshannon** [comment] 2023-05-01 22:07
I can't reproduce this error on my end with those airports. Can you upload your `AppConfig.json` file? It can be found in the `%localappdata%\vATIS-4.0` folder.

**Comment by justinshannon** [comment] 2023-05-01 22:13
Actually disregard, I suspect the error is from a METAR that is missing either the winds or altimeter. I'll have a new build out shortly that should fix that.

**Comment by justinshannon** [comment] 2023-05-05 04:56
This should be fixed in beta 11. If you still have issues, please open a new issue.

**Closed by justinshannon** 2023-05-05 04:56 UTC
