### ISSUE TITLE
Frequency Issue

### ISSUE THREAD

**Issue by Hobsy01** [vatis-project/vatis#29] opened 2022-04-23 20:01 UTC
Creating a Profile for a specific airport.

I have noticed that the frequency for the airport is 136.200, when entering the frequency in and then selecting apply the frequency changes to 135.975. The program will not allow me to set the frequency I want to put in.

**Comment by justinshannon** [comment] 2022-04-24 21:28
Duplicate of #26

**Closed by justinshannon** 2022-04-24 21:28 UTC
